spring:
  application:
    name: spring-config
  cloud:
    config:
      server:
        git:
          uri: file://F:/git_workspace/github_spring_cloud_config #${user.home}为当前路径
#          uri: https://github.com/a46461440/spring-cloud-config-test/
#          search-paths: blob/
#          username: 496461440@qq.com
#          password: Aa412629
server:
  port: 8888

